### ISSUE TITLE
Search Results Customization

### ISSUE THREAD

**Issue by ewlarson** [jhu-sheridan-libraries/geoblacklight#25]
Search results design should match UI mockup.

**Comment by ewlarson** [comment]
## Mockup

![Search Results](https://user-images.githubusercontent.com/69827/74553423-f9644c80-4f1c-11ea-94a3-71fc69c576eb.jpg)

**Comment by ewlarson** [comment]
## Current Screenshot

![JHU GeoPortal Search Results](https://user-images.githubusercontent.com/69827/74553707-81e2ed00-4f1d-11ea-8407-292302a31568.png)

**Comment by ewlarson** [comment]
### Todos

- [X] Facet order
- [X] Facet labels
- [X] Search constraint customizations 
- [ ] Sort options
- [ ] Per page options
- [ ] Map clusters
- [ ] List (thumbnails) vs. Map (default) view
- [X] System tests

**Comment by ewlarson** [comment]
Closed with https://github.com/jhu-sheridan-libraries/geoblacklight/pull/26
